name: SimpleLay
main: brokiem\simplelay\SimpleLay
version: 3.0.0
api: [ 4.0.0 ]
author: brokiem

commands:
  simplelay:
    description: "SimpleLay plugin credits and command list"
    permission: simplelay.simplelay
  lay:
    description: "lay on a block"
    permission: simplelay.lay
    usage: /lay
  sit:
    description: "sit on a block"
    permission: simplelay.sit
    usage: /sit
  sittoggle:
    description: "toggle sit when tapping block"
    permission: simplelay.sittoggle
    usage: /sittoggle
  skick:
    description: "kick the player from a sitting or laying location"
    permission: simplelay.skick
    usage: /skick <player>

permissions:
  simplelay.simplelay:
    default: true
    description: "simplelay command permission"
  simplelay.lay:
    default: true
    description: "permission to allow the use of lay command"
  simplelay.sit:
    default: true
    description: "permission to allow the use of sit command"
  simplelay.sittoggle:
    default: true
    description: "permission to allow the use of sittoggle command"
  simplelay.skick:
    default: op
    description: "permission to allow the use of skick command"
